#pragma once
// #define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
// #define AUTO_SHIFT_TIMEOUT 135
#define LAYER_LOCK_IDLE_TIMEOUT 16000  // 16s

// #define COMBO_ONLY_FROM_LAYER 0
#define COMBO_TERM 16

#define TAPPING_TERM_PER_KEY
#define TAPPING_TERM 160
#define TAPPING_TOGGLE 2

#define QUICK_TAP_TERM 0
#define RETRO_TAPPING
#define PERMISSIVE_HOLD

// #define TAB_HOLD_CAPS_DELAY 256  // default: 80

#define ONESHOT_TAP_TOGGLE 2
// #define ONESHOT_TIMEOUT 256
#define ONESHOT_TIMEOUT 2048

#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MAX_SPEED 3
#define MOUSEKEY_WHEEL_MAX_SPEED 1
// #define MOUSEKEY_WHEEL_TIME_TO_MAX 128

#define MAX_DEFERRED_EXECUTORS 10

/* SPACE-SAVING FLAGS */
#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION
#ifndef NO_DEBUG
  #define NO_DEBUG
#endif // !NO_DEBUG
#if !defined(NO_PRINT) && !defined(CONSOLE_ENABLE)
  #define NO_PRINT
#endif // !NO_PRINT
