#define MO_QWER MO(LY_QWER)
#define MO_CLMK MO(LY_CLMK)
#define MO_RAIS MO(LY_RAIS)
#define MO_LOWR MO(LY_LOWR)
#define MO_NUMB MO(LY_NUMB)
#define MO_MOUS MO(LY_MOUS)
#define MO_SCRL MO(LY_SCRL)
#define MO_CNCL MO(LY_CNCL)

#define TO_QWER TO(LY_QWER)
#define TO_CLMK TO(LY_CLMK)
#define TO_RAIS TO(LY_RAIS)
#define TO_LOWR TO(LY_LOWR)
#define TO_NUMB TO(LY_NUMB)
#define TO_MOUS TO(LY_MOUS)
#define TO_SCRL TO(LY_SCRL)
#define TO_CNCL TO(LY_CNCL)

#define TG_QWER TG(LY_QWER)
#define TG_CLMK TG(LY_CLMK)
#define TG_RAIS TG(LY_RAIS)
#define TG_LOWR TG(LY_LOWR)
#define TG_NUMB TG(LY_NUMB)
#define TG_MOUS TG(LY_MOUS)
#define TG_SCRL TG(LY_SCRL)
#define TG_CNCL TG(LY_CNCL)

#define OS_QWER OSL(LY_QWER)
#define OS_CLMK OSL(LY_CLMK)
#define OS_RAIS OSL(LY_RAIS)
#define OS_LOWR OSL(LY_LOWR)
#define OS_NUMB OSL(LY_NUMB)
#define OS_MOUS OSL(LY_MOUS)
#define OS_SCRL OSL(LY_SCRL)
#define OS_CNCL OSL(LY_CNCL)

#define CTRLTAB LCTL(KC_TAB)
#define CTRL_Q LCTL(KC_Q)
#define CTRL_W LCTL(KC_W)
#define CTRL_E LCTL(KC_E)
#define CTRL_R LCTL(KC_R)
#define CTRL_T LCTL(KC_T)
#define CTRL_Y LCTL(KC_Y)
#define CTRL_U LCTL(KC_U)
#define CTRL_I LCTL(KC_I)
#define CTRL_O LCTL(KC_O)
#define CTRL_P LCTL(KC_P)
#define CTRL_A LCTL(KC_A)
#define CTRL_S LCTL(KC_S)
#define CTRL_D LCTL(KC_D)
#define CTRL_F LCTL(KC_F)
#define CTRL_G LCTL(KC_G)
#define CTRL_H LCTL(KC_H)
#define CTRL_J LCTL(KC_J)
#define CTRL_K LCTL(KC_K)
#define CTRL_L LCTL(KC_L)
#define CTRL_Z LCTL(KC_Z)
#define CTRL_X LCTL(KC_X)
#define CTRL_C LCTL(KC_C)
#define CTRL_V LCTL(KC_V)
#define CTRL_B LCTL(KC_B)
#define CTRL_N LCTL(KC_N)
#define CTRL_M LCTL(KC_M)

#define MT_ESCS MT(MOD_LSFT, KC_ESC)
#define MT_ENTS MT(MOD_RSFT, KC_ENT)
#define MT_TABA MT(MOD_LALT, KC_TAB)  /* LSFT_T(KC_SPC) */
#define MT_LSS MT(MOD_LSFT, KC_SPC)  /* LSFT_T(KC_SPC) */
#define MT_SPC MT(MOD_RSFT, KC_SPC)  /* RSFT_T(KC_SPC) */
/* #define LT_RSFT LT(LY_RAIS, OSM(MOD_RSFT)) */
#define TAB_PRV RCS(KC_TAB)
#define TAB_NXT RCTL(KC_TAB)

#define OSM_ALT OSM(MOD_RALT)

#define SCRN_S3 SCMD(KC_3)
#define SCRN_S4 SCMD(KC_4)
#define SCRN_S5 SCMD(KC_5)

#define THUMB_L KC_LCTL
#define THUMB_R KC_SPC
