BOOTLOADER = caterina
AUTO_SHIFT_ENABLE = no
CAPS_WORD_ENABLE = yes
LAYER_LOCK_ENABLE = yes

COMBO_ENABLE = yes

TAP_DANCE_ENABLE = yes

MOUSE_ENABLE = yes

DEFERRED_EXEC_ENABLE = yes
EXTRAFLAGS += -flto
